package com.costr.tailklicker.GUI;

import java.util.logging.Logger;

public interface Notation {
    String RESET = "\u001B[0m",
            RED = "\u001B[31m",
            BLAU = "\u001B[34m",
            GREEN = "\u001B[32m",
            YELLOW = "\u001B[33m",
            PURPLE = "\u001B[35m",
            CYAN = "\u001B[36m",
            WHITE = "\u001B[37m",
            BLACK = "\u001B[30m",
            BRIGHT_RED = "\u001B[91m",
            BRIGHT_GREEN = "\u001B[92m",
            BRIGHT_YELLOW = "\u001B[93m",
            BRIGHT_BLUE = "\u001B[94m",
            BRIGHT_MAGENTA = "\u001B[95m",
            BRIGHT_CYAN = "\u001B[96m",
            BRIGHT_WHITE = "\u001B[97m",
            BOLD = "\u001B[1m",
            ITALIC = "\u001B[3m",
            UNDERLINE = "\u001B[4m",
            STRIKETHROUGH = "\u001B[9m",
            INVERSE = "\u001B[7m",
            BLACK_BACKGROUND = "\u001B[40m",
            RED_BACKGROUND = "\u001B[41m",
            GREEN_BACKGROUND = "\u001B[42m",
            YELLOW_BACKGROUND = "\u001B[43m",
            BLUE_BACKGROUND = "\u001B[44m",
            MAGENTA_BACKGROUND = "\u001B[45m",
            CYAN_BACKGROUND = "\u001B[46m",
            WHITE_BACKGROUND = "\u001B[47m",
            BRIGHT_BLACK_BACKGROUND = "\u001B[100m",
            BRIGHT_RED_BACKGROUND = "\u001B[101m",
            BRIGHT_GREEN_BACKGROUND = "\u001B[102m",
            BRIGHT_YELLOW_BACKGROUND = "\u001B[103m",
            BRIGHT_BLUE_BACKGROUND = "\u001B[104m",
            BRIGHT_MAGENTA_BACKGROUND = "\u001B[105m",
            BRIGHT_CYAN_BACKGROUND = "\u001B[106m",
            BRIGHT_WHITE_BACKGROUND = "\u001B[107m",
            BOLD_RED = BOLD + RED,
            BOLD_GREEN = BOLD + GREEN,
            BOLD_YELLOW = BOLD + YELLOW,
            BOLD_BLUE = BOLD + BLAU,
            BOLD_MAGENTA = BOLD + PURPLE,
            BOLD_CYAN = BOLD + CYAN,
            BOLD_WHITE = BOLD + WHITE,
            BOLD_BLACK = BOLD + BLACK,
            BOLD_BRIGHT_RED = BOLD + BRIGHT_RED,
            BOLD_BRIGHT_GREEN = BOLD + BRIGHT_GREEN,
            BOLD_BRIGHT_YELLOW = BOLD + BRIGHT_YELLOW,
            BOLD_BRIGHT_BLUE = BOLD + BRIGHT_BLUE,
            BOLD_BRIGHT_MAGENTA = BOLD + BRIGHT_MAGENTA,
            BOLD_BRIGHT_CYAN = BOLD + BRIGHT_CYAN,
            BOLD_BRIGHT_WHITE = BOLD + BRIGHT_WHITE,
            BOLD_BLACK_BACKGROUND = BOLD + BLACK_BACKGROUND,
            BOLD_RED_BACKGROUND = BOLD + RED_BACKGROUND,
            BOLD_GREEN_BACKGROUND = BOLD + GREEN_BACKGROUND,
            BOLD_YELLOW_BACKGROUND = BOLD + YELLOW_BACKGROUND,
            BOLD_BLUE_BACKGROUND = BOLD + BLUE_BACKGROUND,
            BOLD_MAGENTA_BACKGROUND = BOLD + MAGENTA_BACKGROUND,
            BOLD_CYAN_BACKGROUND = BOLD + CYAN_BACKGROUND,
            BOLD_WHITE_BACKGROUND = BOLD + WHITE_BACKGROUND;

    Logger LOGGER = Logger.getLogger(Notation.class.getName());
}